// Vehicle plate-code (kode plat nomor) prefix for each kota/kabupaten in
// lib/wilayah.ts — powers the Kode Customer format (see lib/counters.ts's
// nextCustomerCode): {plat}{YY}{MM}{4-digit seq}, e.g. "B26080001" for a
// Jakarta customer created August 2026. Sourced from samsat.info's
// "Daftar Lengkap Kode Plat Nomor Polisi Kendaraan Daerah di Indonesia",
// 2026-08-25 — a real reference (TNKB region codes), not invented, though
// not the same thing as an official Korlantas document. Per the user's
// request 2026-08-25.
export const PLATE_CODE_BY_KOTA: Record<string, string> = {
  "Kab. Aceh Barat": "BL",
  "Kab. Aceh Barat Daya": "BL",
  "Kab. Aceh Besar": "BL",
  "Kab. Aceh Jaya": "BL",
  "Kab. Aceh Selatan": "BL",
  "Kab. Aceh Singkil": "BL",
  "Kab. Aceh Tamiang": "BL",
  "Kab. Aceh Tengah": "BL",
  "Kab. Aceh Tenggara": "BL",
  "Kab. Aceh Timur": "BL",
  "Kab. Aceh Utara": "BL",
  "Kab. Agam": "BA",
  "Kab. Alor": "EB",
  "Kab. Asahan": "BK",
  "Kab. Asmat": "PA",
  "Kab. Badung": "DK",
  "Kab. Balangan": "DA",
  "Kab. Bandung": "D",
  "Kab. Bandung Barat": "D",
  "Kab. Banggai": "DN",
  "Kab. Banggai Kepulauan": "DN",
  "Kab. Banggai Laut": "DN",
  "Kab. Bangka": "BN",
  "Kab. Bangka Barat": "BN",
  "Kab. Bangka Selatan": "BN",
  "Kab. Bangka Tengah": "BN",
  "Kab. Bangkalan": "M",
  "Kab. Bangli": "DK",
  "Kab. Banjar": "DA",
  "Kab. Banjarnegara": "R",
  "Kab. Bantaeng": "DD",
  "Kab. Bantul": "AB",
  "Kab. Banyuasin": "BG",
  "Kab. Banyumas": "R",
  "Kab. Banyuwangi": "P",
  "Kab. Barito Kuala": "DA",
  "Kab. Barito Selatan": "KH",
  "Kab. Barito Timur": "KH",
  "Kab. Barito Utara": "KH",
  "Kab. Barru": "DP",
  "Kab. Batang": "G",
  "Kab. Batanghari": "BH",
  "Kab. Batu Bara": "BK",
  "Kab. Bekasi": "B",
  "Kab. Belitung": "BN",
  "Kab. Belitung Timur": "BN",
  "Kab. Belu": "DH",
  "Kab. Bener Meriah": "BL",
  "Kab. Bengkalis": "BM",
  "Kab. Bengkayang": "KB",
  "Kab. Bengkulu Selatan": "BD",
  "Kab. Bengkulu Tengah": "BD",
  "Kab. Bengkulu Utara": "BD",
  "Kab. Berau": "KT",
  "Kab. Biak Numfor": "PA",
  "Kab. Bima": "EA",
  "Kab. Bintan": "BP",
  "Kab. Bireun": "BL",
  "Kab. Blitar": "AG",
  "Kab. Blora": "K",
  "Kab. Boalemo": "DM",
  "Kab. Bogor": "F",
  "Kab. Bojonegoro": "S",
  "Kab. Bolaang Mangondow": "DB",
  "Kab. Bolaang Mangondow Selatan": "DB",
  "Kab. Bolaang Mangondow Timur": "DB",
  "Kab. Bolaang Mangondow Utara": "DB",
  "Kab. Bombana": "DT",
  "Kab. Bondowoso": "P",
  "Kab. Bone": "DW",
  "Kab. Bone Bolango": "DM",
  "Kab. Boven Digoel": "PA",
  "Kab. Boyolali": "AD",
  "Kab. Brebes": "G",
  "Kab. Buleleng": "DK",
  "Kab. Bulukumba": "DD",
  "Kab. Bulungan": "KU",
  "Kab. Bungo": "BH",
  "Kab. Buol": "DN",
  "Kab. Buru": "DE",
  "Kab. Buru Selatan": "DE",
  "Kab. Buton": "DT",
  "Kab. Buton Selatan": "DT",
  "Kab. Buton Tengah": "DT",
  "Kab. Buton Utara": "DT",
  "Kab. Ciamis": "Z",
  "Kab. Cianjur": "F",
  "Kab. Cilacap": "R",
  "Kab. Cirebon": "E",
  "Kab. Dairi": "BB",
  "Kab. Deiyai": "PA",
  "Kab. Deli Serdang": "BK",
  "Kab. Demak": "H",
  "Kab. Dharmasraya": "BA",
  "Kab. Dogiyai": "PA",
  "Kab. Dompu": "EA",
  "Kab. Donggala": "DN",
  "Kab. Empat Lawang": "BG",
  "Kab. Ende": "EB",
  "Kab. Enrekang": "DP",
  "Kab. Fak Fak": "PB",
  "Kab. Flores Timur": "EB",
  "Kab. Garut": "Z",
  "Kab. Gayo Lues": "BL",
  "Kab. Gianyar": "DK",
  "Kab. Gorontalo": "DM",
  "Kab. Gorontalo Utara": "DM",
  "Kab. Gowa": "DD",
  "Kab. Gresik": "W",
  "Kab. Grobogan": "K",
  "Kab. Gunung Kidul": "AB",
  "Kab. Gunung Mas": "KH",
  "Kab. Halmahera Barat": "DG",
  "Kab. Halmahera Selatan": "DG",
  "Kab. Halmahera Tengah": "DG",
  "Kab. Halmahera Timur": "DG",
  "Kab. Halmahera Utara": "DG",
  "Kab. Hulu Sungai Selatan": "DA",
  "Kab. Hulu Sungai Tengah": "DA",
  "Kab. Hulu Sungai Utara": "DA",
  "Kab. Humbang Hasundutan": "BB",
  "Kab. Indragiri Hilir": "BM",
  "Kab. Indragiri Hulu": "BM",
  "Kab. Indramayu": "E",
  "Kab. Intan Jaya": "PA",
  "Kab. Jayapura": "PA",
  "Kab. Jayawijaya": "PA",
  "Kab. Jember": "P",
  "Kab. Jembrana": "DK",
  "Kab. Jeneponto": "DD",
  "Kab. Jepara": "K",
  "Kab. Jombang": "W",
  "Kab. Kaimana": "PB",
  "Kab. Kampar": "BM",
  "Kab. Kapuas": "KH",
  "Kab. Kapuas Hulu": "KB",
  "Kab. Karanganyar": "AD",
  "Kab. Karangasem": "DK",
  "Kab. Karawang": "T",
  "Kab. Karimun": "BP",
  "Kab. Karo": "BK",
  "Kab. Katingan": "KH",
  "Kab. Kaur": "BD",
  "Kab. Kayong Utara": "KB",
  "Kab. Kebumen": "AA",
  "Kab. Kediri": "AG",
  "Kab. Keerom": "PA",
  "Kab. Kendal": "H",
  "Kab. Kepahiang": "BD",
  "Kab. Kepulauan Anambas": "BP",
  "Kab. Kepulauan Aru": "DE",
  "Kab. Kepulauan Mentawai": "BA",
  "Kab. Kepulauan Meranti": "BM",
  "Kab. Kepulauan Sangihe": "DL",
  "Kab. Kepulauan Selayar": "DD",
  "Kab. Kepulauan Seribu": "B",
  "Kab. Kepulauan Siau Tagulandang Biaro": "DL",
  "Kab. Kepulauan Sula": "DG",
  "Kab. Kepulauan Talaud": "DL",
  "Kab. Kepulauan Yapen": "PA",
  "Kab. Kerinci": "BH",
  "Kab. Ketapang": "KB",
  "Kab. Klaten": "AD",
  "Kab. Klungkung": "DK",
  "Kab. Kolaka": "DT",
  "Kab. Kolaka Timur": "DT",
  "Kab. Kolaka Utara": "DT",
  "Kab. Konawe": "DT",
  "Kab. Konawe Kepulauan": "DT",
  "Kab. Konawe Selatan": "DT",
  "Kab. Konawe Utara": "DT",
  "Kab. Kotabaru": "DA",
  "Kab. Kotawaringin Barat": "KH",
  "Kab. Kotawaringin Timur": "KH",
  "Kab. Kuantan Singingi": "BM",
  "Kab. Kubu Raya": "KB",
  "Kab. Kudus": "K",
  "Kab. Kulon Progo": "AB",
  "Kab. Kuningan": "E",
  "Kab. Kupang": "DH",
  "Kab. Kutai Barat": "KT",
  "Kab. Kutai Kertanegara": "KT",
  "Kab. Kutai Timur": "KT",
  "Kab. Labuhan Batu": "BK",
  "Kab. Labuhanbatu Selatan": "BK",
  "Kab. Labuhanbatu Utara": "BK",
  "Kab. Lahat": "BG",
  "Kab. Lamandau": "KH",
  "Kab. Lamongan": "S",
  "Kab. Lampung Barat": "BE",
  "Kab. Lampung Selatan": "BE",
  "Kab. Lampung Tengah": "BE",
  "Kab. Lampung Timur": "BE",
  "Kab. Lampung Utara": "BE",
  "Kab. Landak": "KB",
  "Kab. Langkat": "BK",
  "Kab. Lanny Jaya": "PA",
  "Kab. Lebak": "A",
  "Kab. Lebong": "BD",
  "Kab. Lembata": "EB",
  "Kab. Lima Puluh Kota": "BA",
  "Kab. Lingga": "BP",
  "Kab. Lombok Barat": "DR",
  "Kab. Lombok Tengah": "DR",
  "Kab. Lombok Timur": "DR",
  "Kab. Lombok Utara": "DR",
  "Kab. Lumajang": "N",
  "Kab. Luwu": "DP",
  "Kab. Luwu Timur": "DP",
  "Kab. Luwu Utara": "DP",
  "Kab. Madiun": "AE",
  "Kab. Magelang": "AA",
  "Kab. Magetan": "AE",
  "Kab. Mahakam Ulu": "KT",
  "Kab. Majalengka": "E",
  "Kab. Majene": "DC",
  "Kab. Malaka": "DH",
  "Kab. Malang": "N",
  "Kab. Malinau": "KU",
  "Kab. Maluku Barat Daya": "DE",
  "Kab. Maluku Tengah": "DE",
  "Kab. Maluku Tenggara": "DE",
  "Kab. Maluku Tenggara Barat": "DE",
  "Kab. Mamasa": "DC",
  "Kab. Mamberamo Raya": "PA",
  "Kab. Mamberamo Tengah": "PA",
  "Kab. Mamuju": "DC",
  "Kab. Mamuju Tengah": "DC",
  "Kab. Mamuju Utara": "DC",
  "Kab. Mandailing Natal": "BB",
  "Kab. Manggarai": "EB",
  "Kab. Manggarai Barat": "EB",
  "Kab. Manggarai Timur": "EB",
  "Kab. Manokwari": "PB",
  "Kab. Manokwari Selatan": "PB",
  "Kab. Mappi": "PA",
  "Kab. Maros": "DD",
  "Kab. Maybrat": "PB",
  "Kab. Melawi": "KB",
  "Kab. Mempawah": "KB",
  "Kab. Merangin": "BH",
  "Kab. Merauke": "PA",
  "Kab. Mesuji": "BE",
  "Kab. Mimika": "PA",
  "Kab. Minahasa": "DB",
  "Kab. Minahasa Selatan": "DB",
  "Kab. Minahasa Tenggara": "DB",
  "Kab. Minahasa Utara": "DB",
  "Kab. Mojokerto": "W",
  "Kab. Morowali": "DN",
  "Kab. Morowali Utara": "DN",
  "Kab. Muara Enim": "BG",
  "Kab. Muaro Jambi": "BH",
  "Kab. Muko Muko": "BD",
  "Kab. Muna": "DT",
  "Kab. Muna Barat": "DT",
  "Kab. Murung Raya": "KH",
  "Kab. Musi Banyuasin": "BG",
  "Kab. Musi Rawas": "BG",
  "Kab. Musi Rawas Utara": "BG",
  "Kab. Nabire": "PA",
  "Kab. Nagan Raya": "BL",
  "Kab. Nagekeo": "EB",
  "Kab. Natuna": "BP",
  "Kab. Nduga": "PA",
  "Kab. Ngada": "EB",
  "Kab. Nganjuk": "AG",
  "Kab. Ngawi": "AE",
  "Kab. Nias": "BB",
  "Kab. Nias Barat": "BB",
  "Kab. Nias Selatan": "BB",
  "Kab. Nias Utara": "BB",
  "Kab. Nunukan": "KU",
  "Kab. Ogan Ilir": "BG",
  "Kab. Ogan Komering Ilir": "BG",
  "Kab. Ogan Komering Ulu": "BG",
  "Kab. Ogan Komering Ulu Selatan": "BG",
  "Kab. Ogan Komering Ulu Timur": "BG",
  "Kab. Pacitan": "AE",
  "Kab. Padang Lawas": "BB",
  "Kab. Padang Lawas Utara": "BB",
  "Kab. Padang Pariaman": "BA",
  "Kab. Pakpak Bharat": "BB",
  "Kab. Pamekasan": "M",
  "Kab. Pandeglang": "A",
  "Kab. Pangandaran": "Z",
  "Kab. Pangkajene Kepulauan": "DD",
  "Kab. Paniai": "PA",
  "Kab. Parigi Moutong": "DN",
  "Kab. Pasaman": "BA",
  "Kab. Pasaman Barat": "BA",
  "Kab. Paser": "KT",
  "Kab. Pasuruan": "N",
  "Kab. Pati": "K",
  "Kab. Pegunungan Arfak": "PB",
  "Kab. Pegunungan Bintang": "PA",
  "Kab. Pekalongan": "G",
  "Kab. Pelalawan": "BM",
  "Kab. Pemalang": "G",
  "Kab. Penajam Paser Utara": "KT",
  "Kab. Penukal Abab Lematang Ilir": "BG",
  "Kab. Pesawaran": "BE",
  "Kab. Pesisir Barat": "BE",
  "Kab. Pesisir Selatan": "BA",
  "Kab. Pidie": "BL",
  "Kab. Pidie Jaya": "BL",
  "Kab. Pinrang": "DP",
  "Kab. Pohuwato": "DM",
  "Kab. Polowali Mandar": "DC",
  "Kab. Ponorogo": "AE",
  "Kab. Poso": "DN",
  "Kab. Pringsewu": "BE",
  "Kab. Probolinggo": "N",
  "Kab. Pulang Pisau": "KH",
  "Kab. Pulau Morotai": "DG",
  "Kab. Pulau Taliabu": "DG",
  "Kab. Puncak": "PA",
  "Kab. Puncak Jaya": "PA",
  "Kab. Purbalingga": "R",
  "Kab. Purwakarta": "T",
  "Kab. Purworejo": "AA",
  "Kab. Raja Ampat": "PB",
  "Kab. Rejang Lebong": "BD",
  "Kab. Rembang": "K",
  "Kab. Rokan Hilir": "BM",
  "Kab. Rokan Hulu": "BM",
  "Kab. Rote Ndao": "DH",
  "Kab. Sabu Raijua": "DH",
  "Kab. Sambas": "KB",
  "Kab. Samosir": "BB",
  "Kab. Sampang": "M",
  "Kab. Sanggau": "KB",
  "Kab. Sarmi": "PA",
  "Kab. Sarolangun": "BH",
  "Kab. Sekadau": "KB",
  "Kab. Seluma": "BD",
  "Kab. Semarang": "H",
  "Kab. Seram Bagian Barat": "DE",
  "Kab. Seram Bagian Timur": "DE",
  "Kab. Serang": "A",
  "Kab. Serdang Bedagai": "BK",
  "Kab. Seruyan": "KH",
  "Kab. Siak": "BM",
  "Kab. Sidenreng Rappang": "DP",
  "Kab. Sidoarjo": "W",
  "Kab. Sigi": "DN",
  "Kab. Sijunjung": "BA",
  "Kab. Sikka": "EB",
  "Kab. Simalungun": "BK",
  "Kab. Simeulue": "BL",
  "Kab. Sinjai": "DD",
  "Kab. Sintang": "KB",
  "Kab. Situbondo": "P",
  "Kab. Sleman": "AB",
  "Kab. Solok": "BA",
  "Kab. Solok Selatan": "BA",
  "Kab. Soppeng": "DW",
  "Kab. Sorong": "PB",
  "Kab. Sorong Selatan": "PB",
  "Kab. Sragen": "AD",
  "Kab. Subang": "T",
  "Kab. Sukabumi": "F",
  "Kab. Sukamara": "KH",
  "Kab. Sukoharjo": "AD",
  "Kab. Sumba Barat": "ED",
  "Kab. Sumba Barat Daya": "ED",
  "Kab. Sumba Tengah": "ED",
  "Kab. Sumba Timur": "ED",
  "Kab. Sumbawa": "EA",
  "Kab. Sumbawa Barat": "EA",
  "Kab. Sumedang": "Z",
  "Kab. Sumenep": "M",
  "Kab. Supiori": "PA",
  "Kab. Tabalong": "DA",
  "Kab. Tabanan": "DK",
  "Kab. Takalar": "DD",
  "Kab. Tambrauw": "PB",
  "Kab. Tana Tidung": "KU",
  "Kab. Tana Toraja": "DP",
  "Kab. Tanah Bambu": "DA",
  "Kab. Tanah Datar": "BA",
  "Kab. Tanah Laut": "DA",
  "Kab. Tangerang": "B",
  "Kab. Tanggamus": "BE",
  "Kab. Tanjung Jabung Barat": "BH",
  "Kab. Tanjung Jabung Timur": "BH",
  "Kab. Tapanuli Selatan": "BB",
  "Kab. Tapanuli Tengah": "BB",
  "Kab. Tapanuli Utara": "BB",
  "Kab. Tapin": "DA",
  "Kab. Tasikmalaya": "Z",
  "Kab. Tebo": "BH",
  "Kab. Tegal": "G",
  "Kab. Teluk Bintuni": "PB",
  "Kab. Teluk Wondama": "PB",
  "Kab. Temanggung": "AA",
  "Kab. Timor Tengah Selatan": "DH",
  "Kab. Timor Tengah Utara": "DH",
  "Kab. Toba Samosir": "BB",
  "Kab. Tojo Una-Una": "DN",
  "Kab. Toli-Toli": "DN",
  "Kab. Tolikara": "PA",
  "Kab. Toraja Utara": "DP",
  "Kab. Trenggalek": "AG",
  "Kab. Tuban": "S",
  "Kab. Tulang Bawang": "BE",
  "Kab. Tulangbawang Barat": "BE",
  "Kab. Tulungagung": "AG",
  "Kab. Wajo": "DW",
  "Kab. Wakatobi": "DT",
  "Kab. Waropen": "PA",
  "Kab. Way Kanan": "BE",
  "Kab. Wonogiri": "AD",
  "Kab. Wonosobo": "AA",
  "Kab. Yahukimo": "PA",
  "Kab. Yalimo": "PA",
  "Kota Ambon": "DE",
  "Kota Balikpapan": "KT",
  "Kota Banda Aceh": "BL",
  "Kota Bandar Lampung": "BE",
  "Kota Bandung": "D",
  "Kota Banjar": "DA",
  "Kota Banjarbaru": "DA",
  "Kota Banjarmasin": "DA",
  "Kota Batam": "BP",
  "Kota Batu": "N",
  "Kota Bau Bau": "DT",
  "Kota Bekasi": "B",
  "Kota Bengkulu": "BD",
  "Kota Bima": "EA",
  "Kota Binjai": "BK",
  "Kota Bitung": "DB",
  "Kota Blitar": "AG",
  "Kota Bogor": "F",
  "Kota Bontang": "KT",
  "Kota Bukittinggi": "BA",
  "Kota Cilegon": "A",
  "Kota Cimahi": "D",
  "Kota Cirebon": "E",
  "Kota Denpasar": "DK",
  "Kota Depok": "B",
  "Kota Dumai": "BM",
  "Kota Gorontalo": "DM",
  "Kota Gunung Sitoli": "BB",
  "Kota Jakarta Barat": "B",
  "Kota Jakarta Pusat": "B",
  "Kota Jakarta Selatan": "B",
  "Kota Jakarta Timur": "B",
  "Kota Jakarta Utara": "B",
  "Kota Jambi": "BH",
  "Kota Jayapura": "PA",
  "Kota Kediri": "AG",
  "Kota Kendari": "DT",
  "Kota Kotamobagu": "DB",
  "Kota Kupang": "DH",
  "Kota Langsa": "BL",
  "Kota Lhokseumawe": "BL",
  "Kota Lubuk Linggau": "BG",
  "Kota Madiun": "AE",
  "Kota Magelang": "AA",
  "Kota Makasar": "DP",
  "Kota Malang": "N",
  "Kota Manado": "DB",
  "Kota Mataram": "DR",
  "Kota Medan": "BK",
  "Kota Metro": "BE",
  "Kota Mojokerto": "W",
  "Kota Padang": "BA",
  "Kota Padang Panjang": "BA",
  "Kota Padang Sidempuan": "BB",
  "Kota Pagar Alam": "BG",
  "Kota Palangkaraya": "KH",
  "Kota Palembang": "BG",
  "Kota Palopo": "DP",
  "Kota Palu": "DN",
  "Kota Pangkal Pinang": "BN",
  "Kota Pare Pare": "DP",
  "Kota Pariaman": "BA",
  "Kota Pasuruan": "N",
  "Kota Payakumbuh": "BA",
  "Kota Pekalongan": "G",
  "Kota Pekan Baru": "BM",
  "Kota Pematang Siantar": "BK",
  "Kota Pontianak": "KB",
  "Kota Prabumulih": "BG",
  "Kota Probolinggo": "N",
  "Kota Sabang": "BL",
  "Kota Salatiga": "H",
  "Kota Samarinda": "KT",
  "Kota Sawhlunto": "BA",
  "Kota Semarang": "H",
  "Kota Serang": "A",
  "Kota Sibolga": "BB",
  "Kota Singkawang": "KB",
  "Kota Solok": "BA",
  "Kota Sorong": "PB",
  "Kota Subulussalam": "BL",
  "Kota Sukabumi": "F",
  "Kota Sungai Penuh": "BH",
  "Kota Surabaya": "L",
  "Kota Surakarta": "AD",
  "Kota Tangerang": "B",
  "Kota Tangerang Selatan": "B",
  "Kota Tanjung Balai": "BK",
  "Kota Tanjung Pinang": "BP",
  "Kota Tarakan": "KU",
  "Kota Tasikmalaya": "Z",
  "Kota Tebing Tinggi": "BK",
  "Kota Tegal": "G",
  "Kota Ternate": "DG",
  "Kota Tidore Kepulauan": "DG",
  "Kota Tomohon": "DB",
  "Kota Tual": "DE",
  "Kota Yogyakarta": "AB"
};

/** Falls back to "B" (Jakarta) when kota is empty or not in the table — Kota is optional on the customer form. */
export function getPlateCode(kota?: string): string {
  if (kota && PLATE_CODE_BY_KOTA[kota]) return PLATE_CODE_BY_KOTA[kota];
  return "B";
}
